name: Tests

on:
  push:
    branches:
      - main
      - 'releases/**'
      - 'feature-**'
  pull_request:
    branches:
      - main
      - 'releases/**'
      - 'feature-**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache npm packages
      id: cache-packages
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.cache-packages.outputs.cache-hit != 'true'
      run: npm install

    - name: Run tests
      run: npm run test
